### ISSUE TITLE
utils.MLPCenter issue

### ISSUE THREAD

**Issue by zjz82108008** [thunlp/MoEfication#2]
utils.MLPCenter block seems to be something wrong.
The output of the model was not used in the test section:

                    scores = torch.matmul(acts, patterns) # 512, num_blocks, vary from 0 to 1
                    mask, labels = torch.topk(scores, k=int(num_blocks*0.2), dim=-1)
                    mask = mask > 0
                    pred = model(input)
                    pred = torch.topk(pred, k=int(num_blocks*0.2), dim=-1)[1]

                    for x, m, s in zip(labels, mask, scores):
                        if m.sum().item() == 0:
                            continue
                        x = sum([s[xx] for xx in x.cpu()]).item()
                        y = s.sum().item()
                        acc.append( x / y)
                    cur_acc = np.mean(acc)

**Comment by zzy14** [comment]
Hi, thanks for pointing out this issue. `labels, mask, scores` should be `pred, mask, scores` instead. It has been solved.
