### ISSUE TITLE
How to get the hiddens for adj.py

### ISSUE THREAD

**Issue by WenzhengZhang** [thunlp/MoEfication#4]
Hi,
Thanks for your great work! I have a question about the `--res_path` argument in [https://github.com/thunlp/MoEfication/blob/48971265506cbad00d6bbed8e643034a9acbaeae/moefication/adj.py#L12](adj.py) It should be the hidden states of each T5 layer before ffn if my understanding is correct. How do you get those hidden states?

**Comment by KAIWEILIUCC** [comment]
Hello, I would like to ask a question about the MLP selection.
When I finishing running the commond 'python examples/t5-sst2-inf.py' and tries to run the commond 'python moefication/mlp_select_example.py', I get an error telling me that the file ‘results/t5-base//param_split/encoder.block.0.layer.1.DenseReluDense.wi.weight’ doesn't exist.
This error is from the line 203 in utils.py. 
So, do I need to execute other scripts before executing mlp_select_example.py? Thanks. :)

**Comment by zzy14** [comment]
Hi, sorry for the late response.
Yes, it should be the hidden states of each T5 layer before FFNs. You can use `python examples/t5-sst2-inf.py` to get them.
