### ISSUE TITLE
Issues about MLP selection.

### ISSUE THREAD

**Issue by KAIWEILIUCC** [thunlp/MoEfication#5]
Hello, I would like to ask a question about the MLP selection.
When I finishing running the commond 'python examples/t5-sst2-inf.py' and tries to run the commond 'python moefication/mlp_select_example.py', I get an error telling me that the file ‘results/t5-base//param_split/encoder.block.0.layer.1.DenseReluDense.wi.weight’ doesn't exist.
This error is from the line 203 in utils.py.
So, do I need to execute other scripts before executing mlp_select_example.py? Thanks. :)

**Comment by zzy14** [comment]
Hi, you need to first construct experts by `python moefication/param_cluster_example.py`.

**Comment by KAIWEILIUCC** [comment]
Thank you. :)
