### ISSUE TITLE
Can't run anything

### ISSUE THREAD

**Issue by jubueche** [thunlp/MoEfication#8]
Hi,

I tried a bunch of times now, but I can't run anything in this repo. Can you give instructions how to download the model and where to save it in a little more detail?
In general, one end-to-end demonstration on one of the datasets in the paper would be nice where the model is loaded (with a path that is passed).

All the best,
Julian

**Comment by zzy14** [comment]
Hi Julian,

I have updated [the T5 example](https://github.com/thunlp/MoEfication#t5-examples). Using the default args, you can run T5-base on SST-2 dataset.

**Comment by jubueche** [comment]
Thanks. I generated the 96 experts (k=20) and ran the ground-truth example. However, I only get 93.46 as a score. Also, I don't understand this [line](https://github.com/thunlp/MoEfication/blob/c50bb850307a36f8a0add6123f56ba309a156d13/examples/t5-sst2-gt.py#L75).

I am probably using too small experts/too few k.

All the best,
Julian

**Comment by zzy14** [comment]
Yes, it seems to be correct. The reporter results in Table 2 are based on T5-Large. You can use larger models to get higher scores.

In [this line](https://github.com/thunlp/MoEfication/blob/c50bb850307a36f8a0add6123f56ba309a156d13/examples/t5-sst2-gt.py#L75), we compare the probabilities of two label words, representing "positive" and "negative" respectively. You can check the original paper of T5 for more details (Appendix D).

**Comment by jubueche** [comment]
Ok, that makes sense. I really appreciate it. I have some more questions but will reach out privately. Thanks a lot again.
