### ISSUE TITLE
统计神经元是否激活

### ISSUE THREAD

**Issue by zhangxyyutao** [thunlp/MoEfication#9]
统计神经元是否激活的脚本有吗？另外，只统计训练数据作为输入时的神经元激活与否吗？不需要统计其他非训练集中的数据吗？

**Comment by zzy14** [comment]
统计神经元激活比较简单，您可以按照需求自己实现，一个简单的例子，可以在[这一行](https://github.com/thunlp/MoEfication/blob/c50bb850307a36f8a0add6123f56ba309a156d13/examples/t5-sst2-inf.py#L25)后加一行统计`hidden_states`中0的比例。统计的数据只要具有代表性就可以，在我们的实验里选择了训练集的数据，开发集或者测试集中模型的行为按照我们的经验也是类似的。
